"use client";

import React, { useState } from "react";
import { Download, FileText, Activity, CheckCircle } from "lucide-react";

interface ExportReportProps {
  query: string;
  hypotheses: any[];
  graphData: any;
  papers: any[];
  validationData: any;
  drData: any;
  trialsData: any;
}

function generateHTML(props: ExportReportProps): string {
  const { query, hypotheses, graphData, papers, validationData, drData, trialsData } = props;
  const timestamp = new Date().toISOString();
  
  const hypothesesHTML = hypotheses.map(h => `
    <div style="border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-bottom:12px;">
      <h3 style="margin:0 0 8px 0;color:#1e293b;">${h.title}</h3>
      <p style="color:#64748b;font-size:14px;margin:0 0 8px 0;">${h.description}</p>
      <div style="display:flex;gap:12px;font-size:12px;">
        <span style="color:#3b82f6;">Confidence: ${(h.confidence * 100).toFixed(0)}%</span>
        <span style="color:#8b5cf6;">Novelty: ${(h.novelty_score * 100).toFixed(0)}%</span>
        ${h.verified ? '<span style="color:#10b981;">Verified</span>' : ''}
      </div>
    </div>
  `).join("");
  
  const nodesCount = graphData?.nodes?.length || 0;
  const edgesCount = graphData?.links?.length || 0;
  
  const entitiesHTML = (graphData?.nodes || []).map((n: any) => `
    <tr>
      <td style="padding:8px;border-bottom:1px solid #e2e8f0;">${n.label || n.id}</td>
      <td style="padding:8px;border-bottom:1px solid #e2e8f0;"><span style="background:${n.color || '#94a3b8'};color:white;padding:2px 8px;border-radius:12px;font-size:11px;">${n.type}</span></td>
      <td style="padding:8px;border-bottom:1px solid #e2e8f0;">${((n.confidence || 0.5) * 100).toFixed(0)}%</td>
    </tr>
  `).join("");
  
  const papersHTML = (papers || []).map(p => `
    <div style="border:1px solid #e2e8f0;border-radius:8px;padding:12px;margin-bottom:8px;">
      <h4 style="margin:0 0 4px 0;font-size:14px;color:#1e293b;">${p.title}</h4>
      <p style="font-size:12px;color:#64748b;margin:0;">${p.authors} | ${p.journal} (${p.year}) | ${p.citations} citations</p>
    </div>
  `).join("");
  
  const validationHTML = validationData ? `
    <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;margin-bottom:12px;">
      <h3 style="margin:0 0 8px 0;">Validation Score: ${validationData.overall_score}/100</h3>
      <p style="font-size:14px;color:#64748b;">${validationData.synthesis || ''}</p>
    </div>
  ` : '<p style="color:#94a3b8;">Validation not run</p>';
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Onco-TTT Analysis Report — ${query}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #1e293b; }
    h1 { color: #1e40af; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }
    h2 { color: #334155; margin-top: 32px; }
    .meta { color: #94a3b8; font-size: 12px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 8px; background: #f8fafc; border-bottom: 2px solid #e2e8f0; font-size: 12px; color: #64748b; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 11px; }
  </style>
</head>
<body>
  <h1>Onco-TTT Analysis Report</h1>
  <div class="meta">Query: "${query}" | Generated: ${timestamp} | Platform: Onco-TTT (inventcures.github.io)</div>
  
  <h2>Hypotheses (${hypotheses.length})</h2>
  ${hypothesesHTML || '<p style="color:#94a3b8;">No hypotheses generated</p>'}
  
  <h2>Knowledge Graph (${nodesCount} entities, ${edgesCount} relationships)</h2>
  <table>
    <thead><tr><th>Entity</th><th>Type</th><th>Confidence</th></tr></thead>
    <tbody>${entitiesHTML}</tbody>
  </table>
  
  <h2>Validation</h2>
  ${validationHTML}
  
  <h2>Literature (${papers?.length || 0} papers)</h2>
  ${papersHTML || '<p style="color:#94a3b8;">No papers found</p>'}
  
  <div class="footer">
    This report was generated by Onco-TTT, an open-source AI-powered cancer research platform.<br/>
    Data sources: OpenTargets, Semantic Scholar, ClinicalTrials.gov, AlphaFold, cBioPortal.<br/>
    This is a research tool — all findings should be independently verified.
  </div>
</body>
</html>`;
}

export default function ExportReport(props: ExportReportProps) {
  const [exporting, setExporting] = useState(false);
  
  const handleExport = () => {
    setExporting(true);
    const html = generateHTML(props);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `onco-ttt-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setExporting(false), 1000);
  };
  
  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-1.5 px-3 py-1.5 bg-white border border-slate-200 hover:border-blue-400 hover:text-blue-600 rounded-lg text-xs font-medium text-slate-600 transition-all shadow-sm"
    >
      {exporting ? <CheckCircle size={14} className="text-emerald-500" /> : <Download size={14} />}
      {exporting ? "Saved!" : "Export Report"}
    </button>
  );
}
