"""Named constants extracted from magic numbers across the codebase."""

# --- Cache ---
EXTRACTION_CACHE_MAX_SIZE = 500
EXTRACTION_CACHE_TTL = 1800.0  # 30 minutes
SEMANTIC_CACHE_MAX_SIZE = 1000
SEMANTIC_SIMILARITY_THRESHOLD = 0.8

# --- Entity Extraction ---
DEFAULT_ENTITY_THRESHOLD = 0.4

# --- HTTP ---
DEFAULT_HTTP_TIMEOUT = 60.0

# --- Knowledge Graph ---
SPRING_LAYOUT_ITERATIONS = 80
MAX_HYPOTHESES = 5
ACTIVATION_GLOW_THRESHOLD = 0.5
MAX_NODE_RADIUS = 42
DEFAULT_NODE_RADIUS = 22
ACTIVATION_RADIUS_BOOST = 0.3

# --- Simulation ---
PROPAGATION_DECAY = 0.6
PROPAGATION_MAX_HOPS = 4
PROPAGATION_EFFECT_THRESHOLD = 0.05
MAX_AFFECTED_NODES_RETURNED = 30

# --- Dossier Scoring Weights ---
DOSSIER_WEIGHT_VALIDATION = 0.30
DOSSIER_WEIGHT_DRUGGABILITY = 0.20
DOSSIER_WEIGHT_IP_FREEDOM = 0.15
DOSSIER_WEIGHT_CLINICAL = 0.15
DOSSIER_WEIGHT_MODEL = 0.10
DOSSIER_WEIGHT_LITERATURE = 0.10
TRIAL_SWEET_SPOT_MAX = 20
